# Site settings
title:          Avamposto del Male
description:    "Il Male&trade; ha un nuovo scopo."
url:            "https://eviloutpost.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Site info
author:
  name:         EvilOutpost
  url:          https://eviloutpost.github.io
  email:        eviloutpost@gmail.com

# Authors, as shown in Jekyill tutorial
collections:
  authors:
    output: true

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
