# Site settings
title:          Avamposto del Male
description:    "Il Male&trade; ha un Nuovo Scopo."
url:            "https://eviloutpost.github.io"

# Google Analytics
google_analytics: UA-128102222-1

# Site info
author:
  name:         Evil Outpost
  url:          https://eviloutpost.github.io
  email:        eviloutpost@gmail.com
logo:           /assets/eviloutpost.png
social:
  links:
    - https://www.facebook.com/eviloutpost/
    - https://eviloutpost.tumblr.com/
    - https://www.instagram.com/eviloutpost/

# Authors, as shown in Jekyill tutorial
collections:
  authors:
    output: true
  works:
    output: true

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
